


var myApp;

myApp = angular.module('myApp', [
  'ngAutocomplete',
  'ui-leaflet'
]);

myApp.controller('myController', ['$scope', 'leafletData', '$timeout', '$document', function($scope, leafletData, $timeout, $dom){
  angular.extend($scope, {
    hcm: {
      lat: 10.792489,
      lng: 106.656661,
      zoom: 10
    },
    maxbounds: {
      northEast: {
        lat: 11.236193,
        lng: 107.266673
      },
      southWest: {
        lat: 10.349058,
        lng: 106.226371
      }
    },
    defaults: {
      minZoom: 10,
      zoomControlPosition: 'bottomright'
    },
    layers: {
      baselayers: {
        gray: {
          name: "Bản đồ Gray",
          type: "agsBase",
          layer: "Gray",
          visible: true
        }
      },
      overlays: {
        basegis: {
          name: "Bản đồ nền TP.HCM",
          type: "agsDynamic",
          url: "http://hcmgisportal.vn:6080/arcgis/rest/services/BaseMap_LIDAR/MapServer",
          visible: true
        },
        qtiles: {
          name: "Ảnh hàng không (Cache)",
          type: "xyz",
          url: "http://hcmgisportal.vn/basemap/cache_lidar/{z}/{x}/{y}.jpg",
          visible: false
        },
        trueorthor: {
          name: "Ảnh hàng không",
          type: "agsImage",
          url: "http://hcmgisportal.vn:6080/arcgis/rest/services/TRUEORTHOR_LIDAR/ImageServer",
          visible: false,
          position: 'back'
        },
        gt_hcm: {
          name: "Lớp giao thông TP.HCM",
          type: "agsDynamic",
          url: "http://hcmgisportal.vn:6080/arcgis/rest/services/BaseMap_LIDAR_gt/MapServer",
          visible: false
        },
      }
    }
  });





  leafletData.getMap().then(function(map){

    //var layer = L.esri.basemapLayer("Gray");
    //var hcm_basemap = L.esri.dynamicMapLayer({
    //  url: 'http://hcmgisportal.vn:6080/arcgis/rest/services/BaseMap_HCM/MapServer',
    //  opacity: 1,
    //  useCors: false
    //});
    //var lidar = L.esri.imageMapLayer({
    //  url: 'http://hcmgisportal.vn:6080/arcgis/rest/services/TRUEORTHOR_LIDAR/ImageServer',
    //  position: 'back'
    //});
    //var qtiles =L.tileLayer('http://hcmgisportal.vn/basemap/cache_lidar/{z}/{x}/{y}.jpg', {
    //  // maxZoom: 16,
    //  tms: false,
    //  attribution: 'Generated by QTiles'
    //});
    //
    //var blank =L.tileLayer('', {
    //  // maxZoom: 16,
    //  tms: false,
    //  attribution: 'Generated by QTiles'
    //});
    //var gt_hcm = L.esri.dynamicMapLayer({
    //  url: 'http://hcmgisportal.vn:6080/arcgis/rest/services/BaseMap_HCM_gt/MapServer',
    //  opacity: 1,
    //  useCors: false
    //});
    //
    //L.control.layers({
    //  'Bản đồ (trắng)': blank,
    //  'Bản đồ Gray': layer.addTo(map),
    //  'Bản đồ Streets': L.esri.basemapLayer("Streets"),
    //  'Bản đồ Imagery':  L.esri.basemapLayer("Imagery")
    //}, {
    //  'Ảnh hàng không': lidar,
    //  'Bản đồ nền TPHCM': hcm_basemap.addTo(map),
    //  'Ảnh hàng không (Cached)': qtiles,
    //  'Lớp giao thông HCM': gt_hcm
    //}).addTo(map);
    //map.on('zoomend', function() {
    //  if (map.getZoom() > 13) {
    //    map.removeLayer(layer);
    //  } else {
    //    map.addLayer(layer);
    //  }
    //});













    leafletData.getLayers().then(function(layers){
      var basegis = layers.overlays.basegis;
      $dom.find("#basemapslider").slider({
        animate: true,
        value: 1,
        orientation: "vertical",
        min: 0,
        max: 1,
        step: 0.1,
        slide: function (event, ui) {
          basegis.setOpacity(ui.value);
        }
      });
      $dom.find('#basemapslider').mousedown(function(){
        map.dragging.disable();
      })
      $dom.find('#basemapslider').mouseup(function(){
        map.dragging.enable();
      });

      var gray = layers.baselayers.gray;
      $scope.$watch('hcm.zoom', function(newValue){
        if (newValue > 13) {
          map.removeLayer(gray);
        } else {
          map.addLayer(gray);
        }
      });
    })

  })


  $scope.googleAutocomplete = {
    options: {
      country: 'vn',
      watchEnter: true
    }
  }

  $scope.findGoogle = function(){
    leafletData.getMap().then(function(map){
      if($scope.googleAutocomplete.result == ''){
        $scope.googleAutocomplete.details = null;
        //$rootScope.markers.geocode.geolocation = {};
        return;
      }

      if(!$scope.googleAutocomplete.details){
        return false;
      }
      var detail = $scope.googleAutocomplete.details;
      var location = detail.geometry.location;

      $scope.markers = {
        geolocation: {
          lat:location.lat(),
          lng:location.lng(),
          icon: {
            type: 'div',
            iconSize: [32,32],
            html: '<div class="pin1"><span class="circle-radar"></span><span class="circle-pin"></span></div>'
          },
        }
      }

      $timeout(function(){
        $scope.markers = {};
      },8000)

      map.setView([location.lat(), location.lng()], 16);
    })
  }




}])


angular.module('myApp').directive('ngEnter', function () {
  return function (scope, element, attrs) {
    element.bind("keydown keypress", function (event) {
      if(event.which === 13) {
        scope.$apply(function (){
          scope.$eval(attrs.ngEnter);
        });

        event.preventDefault();
      }
    });
  };
});
